"""
Attention Pooling Layer.
"""
from torch import softmax, sum as torch_sum, Tensor
from torch.nn import Module, Sequential, Linear, Tanh


class AttentionPool(Module):
    """
    Attention Pooling Layer.

    This layer computes a weighted sum of the input features using attention scores.
    The attention scores are generated by a small neural network that outputs a score for each
    time step. The scores are then normalized using the softmax function to obtain attention weights.
    Finally, the input features are weighted by these attention weights and summed to produce
    a single output vector.
    """

    def __init__(self, in_features: int, out_hidden: int = 128):
        """
        Attention Pooling Layer.

        This layer computes attention scores for each time step in the input sequence
        using a two-layer neural network with a Tanh activation in between. The scores are
        then normalized using softmax to obtain attention weights, which are used to compute
        a weighted sum of the input features.
        :param in_features: Dimension of the input features.
        :param out_hidden: Dimension of the hidden layer in the attention score network.
        """
        super().__init__()
        self.score = Sequential(
            # First layer transforms input features to hidden dimension
            Linear(in_features, out_hidden), Tanh(),
            # Second layer outputs a single score for each time step
            Linear(out_hidden, 1)
        )

    def forward(self, x: Tensor) -> Tensor:
        """
        Forward pass of the Attention Pooling layer.

        Computes attention scores for each time step, normalizes them using softmax,
        and computes a weighted sum of the input features based on these attention weights.
        :param x:
        :return:
        """
        # Compute attention scores
        a = self.score(x).squeeze(-1)
        # Normalize scores to obtain attention weights
        a = softmax(a, dim=1)
        # Compute weighted sum of input features
        return torch_sum(x * a.unsqueeze(-1), dim=1)
